spring.application.name=booking-service
server.port=${BOOKING_SERVICE_PORT}


spring.datasource.url=${BOOKING_DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL}

eureka.instance.prefer-ip-address=true

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.database=1

spring.kafka.bootstrap-servers=localhost:29092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.cloud.openfeign.circuitbreaker.enabled=true
resilience4j.circuitbreaker.instances.PRODUCT-SERVICE.sliding-window-size=10
resilience4j.circuitbreaker.instances.PRODUCT-SERVICE.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.PRODUCT-SERVICE.wait-duration-in-open-state=10000ms
resilience4j.circuitbreaker.instances.PRODUCT-SERVICE.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.PRODUCT-SERVICE.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.timelimiter.instances.PRODUCT-SERVICE.timeout-duration=5s